name: Frontend CI

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Build frontend
        run: npm run build

  trivy-scan:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t fairshare-frontend .

    - name: Cache Trivy DB
      uses: actions/cache@v4
      with:
        path: ~/.cache/trivy
        key: ${{ runner.os }}-trivy-db-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-trivy-db

    - name: Run Trivy Image Scan
      uses: aquasecurity/trivy-action@0.24.0
      with:
        image-ref: fairshare-frontend
        format: table
        output: trivy-results.log
        severity: HIGH,CRITICAL
        exit-code: "0"

    - name: Show Trivy Table in Logs
      run: cat trivy-results.log

    - name: Upload trivy log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: trivy-container-report
        path: trivy-results.log

  zap-scan:
    needs: trivy-scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    - name: Start frontend
      run: |
        npm run dev &                  # run dev server in background
        npx wait-on http://localhost:5173   # wait for server to be ready

    - name: Run OWASP ZAP Full Scan Action
      uses: zaproxy/action-full-scan@v0.13.0
      with:
        token: ${{ secrets.ZAP_PAT }}
        target: "http://localhost:5173"
        cmd_options: "-I -d"           
        fail_action: false
